name: Build AMI with Packer and Ansible

on:
  push:
    branches:
      - main

jobs:
  build-ami:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout packer_ansible branch
        run: git fetch origin packer_ansible && git checkout packer_ansible

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Install Latest Packer
        run: |
          wget -O packer.zip https://releases.hashicorp.com/packer/1.11.1/packer_1.11.1_linux_amd64.zip
          unzip -o packer.zip
          sudo mv packer /usr/local/bin/
          packer --version  # Verify Packer installation

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region us-east-1  # Replace with your AWS region

      - name: Run Packer build and capture AMI ID
        id: packer
        run: |
          packer build -machine-readable packer/PosgresawsTemplate.json | tee packer_output.txt
          ami_id=$(awk -F, '$0 ~/artifact,0,id/ {print $6}' packer_output.txt)
          echo "ami_id=$ami_id" >> $GITHUB_ENV
          echo "PACKER_AMI_ID=$ami_id" >> $GITHUB_ENV

      - name: Print AMI ID
        run: echo "The generated AMI ID is ${{ env.PACKER_AMI_ID }}"

      - name: Set repository secret with AMI ID
        run: |
          echo "${{ env.PACKER_AMI_ID }}" > ami_id.txt
          gh secret set PACKER_AMI_ID -b"${{ env.PACKER_AMI_ID }}"

      - name: Checkout main branch
        run: git checkout main
