name: Build AMI with Packer and Ansible

on:
  push:
    branches:
      - main

jobs:
  build-ami:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout packer_ansible branch
        run: git fetch origin packer_ansible && git checkout packer_ansible

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Install Packer
        run: |
          if ! command -v packer &> /dev/null
          then
            wget https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
            unzip -o packer_1.7.4_linux_amd64.zip -d packer_install
            sudo mv packer_install/packer /usr/local/bin/
            rm -rf packer_install
          fi
          packer --version  # Verify Packer installation

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region us-east-1  # Replace with your AWS region

      - name: Run Packer build and capture AMI ID
        id: packer
        run: |
          ami_id=$(packer build -machine-readable packer/PosgresawsTemplate.json | tee /dev/tty | awk -F, '$0 ~/artifact,0,id/ {print $6}')
          echo "::set-output name=ami_id::$ami_id"
          echo "${ami_id}" > ami_id.txt  # Store AMI ID in a file

      - name: Print AMI ID
        run: echo "The generated AMI ID is ${{ steps.packer.outputs.ami_id }}"

      - name: Set repository secret with AMI ID
        run: |
          echo "::set-env name=PACKER_AMI_ID::${{ steps.packer.outputs.ami_id }}"
          echo "${{ steps.packer.outputs.ami_id }}" > ami_id.txt
          echo "::set-secret name=PACKER_AMI_ID::$(cat ami_id.txt)"

      - name: Checkout main branch
        run: git checkout main
